### ISSUE TITLE
bug: `KeyError: 'scale'` upon compilation of script

### ISSUE THREAD

**Issue by AgentM12** [SethBling/cbscript#27]
I encounter the following error when running the compile.py:

```py
Compiler encountered unexpected error during compilation:
Traceback (most recent call last):
  File "D:\Dev\Minecraft\CBScript\cbscript\cbscript.py", line 70, in try_to_compile
    success = self.compile_all()
  File "D:\Dev\Minecraft\CBScript\cbscript\cbscript.py", line 106, in compile_all
    global_environment.set_dollarid('global_scale', parsed['scale'])
KeyError: 'scale'
```

This can be resolved by defining the `scale 1` in your `cbscript`. I don't know what this scale is used for, so it might be a good idea to give it an implicit default value of 1 (or whatever is the most sensible default) rather than failing the compilation.

**Comment by CoolCat467** [comment]
#15 has a fix for this among it's other changes, but might work better factored out into it's own pull request.
