### ISSUE TITLE
Examples don't compile

### ISSUE THREAD

**Issue by 837951602** [SethBling/cbscript#47]
```
/tmp/cbscript-master$python3 compile.py '/tmp/cbscript-master/Scripts/left_right_click_detector.cblib' 
WARNING: /tmp/cbscript-master/scriptparse.py:1834: Function p_loot_table_definition redefined. Previously defined on line 1830
Generating LALR tables
WARNING: 154 shift/reduce conflicts
WARNING: 267 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 78 resolved using rule (integer -> DECIMAL)
WARNING: rejected rule (integer -> MINUS DECIMAL) in state 78
WARNING: reduce/reduce conflict in state 79 resolved using rule (integer -> HEX)
WARNING: rejected rule (integer -> MINUS HEX) in state 79
WARNING: reduce/reduce conflict in state 80 resolved using rule (integer -> BINARY)
WARNING: rejected rule (integer -> MINUS BINARY) in state 80
WARNING: reduce/reduce conflict in state 108 resolved using rule (number -> integer)
WARNING: rejected rule (virtualinteger -> integer) in state 108
WARNING: reduce/reduce conflict in state 144 resolved using rule (optnewlines -> newlines)
WARNING: rejected rule (empty -> <empty>) in state 144
WARNING: reduce/reduce conflict in state 239 resolved using rule (float_val -> FLOAT)
WARNING: rejected rule (float_val -> MINUS FLOAT) in state 239
WARNING: reduce/reduce conflict in state 243 resolved using rule (pyid -> DOLLAR ID)
WARNING: rejected rule (virtualinteger -> DOLLAR ID) in state 243
WARNING: reduce/reduce conflict in state 515 resolved using rule (number -> integer)
WARNING: rejected rule (virtualinteger -> integer) in state 515
WARNING: reduce/reduce conflict in state 638 resolved using rule (variable -> COLON data_path)
WARNING: rejected rule (nbt_object -> COLON data_path) in state 638
WARNING: reduce/reduce conflict in state 755 resolved using rule (variable -> ID COLON data_path)
WARNING: rejected rule (nbt_object -> ID COLON data_path) in state 755
WARNING: reduce/reduce conflict in state 850 resolved using rule (pyid -> DOLLAR ID)
WARNING: rejected rule (virtualinteger -> DOLLAR ID) in state 850
WARNING: reduce/reduce conflict in state 931 resolved using rule (pyid -> DOLLAR ID)
WARNING: rejected rule (empty -> <empty>) in state 931
Compiling left_right_click_detector...
Syntax error at line 1 column 14. Unexpected NEWLINE symbol "\n" in state 57.
Unable to parse script.
Script had compile error(s).

^CTraceback (most recent call last):
  File "compile.py", line 30, in <module>
    run()
  File "compile.py", line 28, in run
    time.sleep(1)
KeyboardInterrupt


/tmp/cbscript-master$python3 compile.py '/tmp/cbscript-master/Scripts/music.cblib' 
Compiling music...
Syntax error at line 1 column 10. Unexpected EQUALS symbol "=" in state 123.
Unable to parse script.
Script had compile error(s).

^CTraceback (most recent call last):
  File "compile.py", line 30, in <module>
    run()
  File "compile.py", line 28, in run
    time.sleep(1)
KeyboardInterrupt
```

Don't get what went wrong

**Comment by SethBling** [comment]
.cblib files are include files. .cbscript files are the ones that can compile.

**Comment by 837951602** [comment]
Seems solved
